#!/usr/bin/env bash

get_dns_info() {
    local domain="$1"
    local subdomain="$2"
    local record_types=("A" "CNAME" "MX" "TXT")  # You can add more record types if needed

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        for type in "${record_types[@]}"; do
            result=$(dig +short $sub.$domain $type)
            if [ -n "$result" ]; then
                echo "The subdomain $sub is a $type record and points to $result"
            fi
        done
    done
}

# Check if both domain and subdomain parameters are provided
if [ "$#" -eq 2 ]; then
    get_dns_info "$1" "$2"
elif [ "$#" -eq 1 ]; then
    get_dns_info "$1"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

