#!/usr/bin/env bash
# This script installs and configures HAProxy on a new Ubuntu machine

# Update the package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend web
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
    option http-server-close
    option forwardfor
    http-request add-header X-Served-By %[src]
EOF

# Enable HAProxy service to start on boot
sudo systemctl enable haproxy

# Start HAProxy
sudo systemctl start haproxy

