#!/usr/bin/env bash
# This script runs the whoami command command under the specified user

# Check if an argument is provided
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

# Get the username from the command line argument
username=$1

# Run the whoami command for the specified user
su -c "whoami" $username
